select * from user_users;
select * from all_users;
select * from dba_users;


CREATE USER paula
IDENTIFIED BY paula
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS
PROFILE DEFAULT;

SELECT * FROM dba_profiles;

SELECT tablespace_name FROM dba_tablespaces;

select * from USER_CONS_COLUMNS;

CREATE USER MIGUELANGEL 
IDENTIFIED BY 12345
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO MIGUELANGEL;
select * from all_users;
ALTER USER MIGUELANGEL account unlock;



CREATE PROFILE REPONEDOR LIMIT
  SESSIONS_PER_USER 1
  CONNECT_TIME 2;




