--CREAR TABLAS

--------PERSONAS-----
CREATE TABLE PERSONA (
    NOMBRE VARCHAR2(20),
    APELLIDOS VARCHAR2(40),
    PROFESION VARCHAR2(20),
    CI INTEGER CHECK (CI BETWEEN 150 AND 300),
    EMAIL VARCHAR2(30) UNIQUE CHECK (EMAIL LIKE '%@%'),
    ID_PROYECTO NUMBER(4),
    CONSTRAINT PK_PERSONA PRIMARY KEY (NOMBRE, APELLIDOS),
    CONSTRAINT FK_PERSONA_PROYECTO FOREIGN KEY (ID_PROYECTO)
        REFERENCES PROYECTO(ID_PROYECTO),
    CONSTRAINT CK_PROFESION CHECK (PROFESION IN ('INVESTIGADOR','ADJUNTO','AUXILIAR','ESTUDIANTE'))
);


-----PROYECTO-----

CREATE TABLE PROYECTO (
    ID_PROYECTO NUMBER(4) PRIMARY KEY,
    NOMBRE_PROYECTO VARCHAR2(20) NOT NULL UNIQUE,
    PRESUPUESTO NUMBER(5,2),
    DIRECTOR_NOMBRE VARCHAR2(20),
    DIRECTOR_APELLIDOS VARCHAR2(40)
);

---checkpoint---

CREATE TABLE CHECKPOINT (
    ID_PROYECTO NUMBER(4),
    ID_HOBBY NUMBER(2),
    FECHA DATE DEFAULT SYSDATE,
    PROGRESO INTEGER CHECK (PROGRESO BETWEEN 5 AND 100),
    CONSTRAINT PK_CHECKPOINT PRIMARY KEY (ID_PROYECTO, ID_HOBBY),
    CONSTRAINT FK_CHECKPOINT_PROYECTO FOREIGN KEY (ID_PROYECTO)
        REFERENCES PROYECTO(ID_PROYECTO)
);

---ejercicio1--- insertar personas

INSERT INTO PERSONA VALUES ('SHELDON','COOPER','INVESTIGADOR', 300, 'SHELDON@CALTECH.EDU', NULL);

INSERT INTO PERSONA VALUES ('LEONARD','HOFSTADTER','INVESTIGADOR', 250, 'LEONARD@CALTECH.EDU', NULL);


---ejercicio2---insertar proyecto

INSERT INTO PROYECTO VALUES (1001, 'TEORÍADECUERDAS', 500.00, 'SHELDON', 'COOPER');

INSERT INTO PROYECTO VALUES (1002, 'SISTEMA GUIADO ESP', 750.00, 'HOWARD', 'WOLOWITZ');


---ejercicio3--

ALTER TABLE PERSONA
ADD (
    PAREJA_NOMBRE VARCHAR2(20),
    PAREJA_APELLIDOS VARCHAR2(40),
    CONSTRAINT FK_PAREJA
        FOREIGN KEY (PAREJA_NOMBRE, PAREJA_APELLIDOS)
        REFERENCES PERSONA (NOMBRE, APELLIDOS)
);

INSERT INTO PERSONA VALUES ('HOWARD','WOLOWITZ','INVESTIGADOR', 160, 'HOWARD@CALTECH.EDU', 1002);

INSERT INTO PERSONA VALUES ('BERNADETTE','ROSTENKOWSKI','ADJUNTO', 180, 'BERNADETTE@CALTECH.EDU', 1002);

















